id: P997B477B
initial_creation_type: input
source_metadata:
  title: TYKYN
  language: ug
  volumes:
    709bc6dccdac4fa69c35f38cc6ca7b2b:
      title: Complete text
      base_file: Complete text.txt
      work_id: WC054EA66
  chapter_to_tile: {}
created_at: '2022-03-02T09:14:28.139292'
last_modified_at: '2022-03-02T09:14:28.139313'
